import html2canvas from 'html2canvas'
import { jsPDF } from 'jspdf'

/**
 * Generate and download PDF of analysis results
 * Returns { success: boolean, message: string }
 */
export const downloadResultsAsPDF = async (results, resumeText, jobDescriptionText) => {
  try {
    // Validate results
    if (!results || typeof results.match_percentage !== 'number') {
      return { success: false, message: 'Invalid results data. Please try analyzing again.' }
    }

    // Safely extract data with defaults BEFORE building HTML
    const matchedSkills = Array.isArray(results.matched_skills) ? results.matched_skills : []
    const missingSkills = Array.isArray(results.missing_skills) ? results.missing_skills : []
    const suggestions = Array.isArray(results.improvement_suggestions) ? results.improvement_suggestions : []
    const matchPercentage = results.match_percentage

    // Build matched skills HTML safely
    let matchedSkillsHTML = matchedSkills.length > 0 
      ? matchedSkills.map(skill => `<li style="margin-bottom: 8px; color: #10b981;">✓ ${String(skill)}</li>`).join('')
      : '<li style="margin-bottom: 8px; color: #999;">No matched skills found</li>'

    // Build missing skills HTML safely
    let missingSkillsHTML = missingSkills.length > 0
      ? missingSkills.map(skill => `<li style="margin-bottom: 8px; color: #ef4444;">✗ ${String(skill)}</li>`).join('')
      : '<li style="margin-bottom: 8px; color: #999;">No missing skills identified</li>'

    // Build suggestions HTML safely
    let suggestionsHTML = suggestions.length > 0
      ? suggestions.map((suggestion, index) => `<li style="margin-bottom: 8px; color: #1f2937;">${index + 1}. ${String(suggestion)}</li>`).join('')
      : '<li style="margin-bottom: 8px; color: #999;">No suggestions available</li>'

    // Create a temporary container with the results
    const container = document.createElement('div')
    container.style.position = 'absolute'
    container.style.left = '-9999px'
    container.style.width = '800px'
    container.style.backgroundColor = 'white'
    container.style.padding = '40px'
    container.style.fontFamily = 'Arial, sans-serif'
    
    const scoreColor = getScoreColor(matchPercentage)
    const summaryText = matchPercentage >= 80 
      ? 'You are an excellent fit for this position!' 
      : matchPercentage >= 60 
      ? 'You have good potential for this role.' 
      : 'Consider developing the missing skills listed above.'

    container.innerHTML = `
      <div style="margin-bottom: 30px;">
        <h1 style="color: #0f1419; margin-bottom: 10px;">✨ ChecknNext Analysis Report</h1>
        <p style="color: #4a627f; margin: 0;">AI-Powered Resume-JD Matcher</p>
        <p style="color: #999; font-size: 12px; margin-top: 5px;">${new Date().toLocaleString()}</p>
      </div>

      <div style="border-bottom: 3px solid #0f1419; padding-bottom: 20px; margin-bottom: 30px;">
        <h2 style="color: #1f2937; font-size: 24px; margin: 0 0 10px 0;">Match Score</h2>
        <div style="font-size: 48px; font-weight: bold; color: ${scoreColor};">
          ${matchPercentage}%
        </div>
      </div>

      <div style="margin-bottom: 30px;">
        <h3 style="color: #1f2937; border-bottom: 2px solid #4a627f; padding-bottom: 10px; margin-bottom: 15px;">
          Matched Skills
        </h3>
        <ul style="margin: 0; padding-left: 20px;">
          ${matchedSkillsHTML}
        </ul>
      </div>

      <div style="margin-bottom: 30px;">
        <h3 style="color: #1f2937; border-bottom: 2px solid #ef4444; padding-bottom: 10px; margin-bottom: 15px;">
          Missing Skills
        </h3>
        <ul style="margin: 0; padding-left: 20px;">
          ${missingSkillsHTML}
        </ul>
      </div>

      <div style="margin-bottom: 30px;">
        <h3 style="color: #1f2937; border-bottom: 2px solid #f59e0b; padding-bottom: 10px; margin-bottom: 15px;">
          Recommendations
        </h3>
        <ol style="margin: 0; padding-left: 20px;">
          ${suggestionsHTML}
        </ol>
      </div>

      <div style="background-color: #f3f4f6; padding: 20px; border-radius: 8px; margin-top: 30px;">
        <h4 style="color: #1f2937; margin-top: 0;">Summary</h4>
        <p style="color: #666; margin: 10px 0;">
          Your resume has a <strong>${matchPercentage}%</strong> match with the job description.
          ${summaryText}
        </p>
      </div>

      <div style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e7eb; font-size: 12px; color: #999;">
        <p style="margin: 0;">Generated by ChecknNext - AI Resume-JD Matcher</p>
        <p style="margin: 5px 0 0 0;">www.checknext.app</p>
      </div>
    `

    document.body.appendChild(container)

    document.body.appendChild(container)

    // Convert to canvas with better error handling
    let canvas
    try {
      canvas = await html2canvas(container, {
        backgroundColor: '#ffffff',
        scale: 2,
        useCORS: true,
        allowTaint: true,
        logging: false,
      })
    } catch (canvasError) {
      document.body.removeChild(container)
      return { success: false, message: 'Failed to convert results to image. Please try again.' }
    }

    if (!canvas) {
      document.body.removeChild(container)
      return { success: false, message: 'Canvas generation failed. Please try again.' }
    }

    // Create PDF
    let pdf
    try {
      pdf = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4',
      })
    } catch (pdfError) {
      document.body.removeChild(container)
      return { success: false, message: 'Failed to create PDF document. Please try again.' }
    }

    const imgData = canvas.toDataURL('image/png')
    const pageWidth = pdf.internal.pageSize.getWidth()
    const pageHeight = pdf.internal.pageSize.getHeight()
    
    const imgWidth = pageWidth - 20
    const imgHeight = (canvas.height * imgWidth) / canvas.width
    
    let heightLeft = imgHeight
    let position = 10

    // Add first page
    pdf.addImage(imgData, 'PNG', 10, position, imgWidth, imgHeight)
    heightLeft -= pageHeight - 20

    // Add additional pages if needed
    while (heightLeft >= 0) {
      position = heightLeft - imgHeight + 10
      pdf.addPage()
      pdf.addImage(imgData, 'PNG', 10, position, imgWidth, imgHeight)
      heightLeft -= pageHeight
    }

    // Download
    const fileName = `ChecknNext_Analysis_${new Date().getTime()}.pdf`
    pdf.save(fileName)

    // Cleanup
    document.body.removeChild(container)

    return { success: true, message: 'PDF downloaded successfully!' }
  } catch (error) {
    console.error('Error generating PDF:', error)
    return { success: false, message: `Failed to generate PDF: ${error.message}` }
  }
}

/**
 * Get color based on match percentage
 */
function getScoreColor(percentage) {
  if (percentage >= 80) return '#10b981' // Green
  if (percentage >= 60) return '#4a627f' // Deep Sea
  if (percentage >= 40) return '#f59e0b' // Yellow
  return '#ef4444' // Red
}
